<?php

/*
 * This file is part of Laravel Database.
 *
 * (c) Graham Campbell <graham@mineuk.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace GrahamCampbell\Database\Providers\Common;

use Illuminate\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * This is the paginate provider trait.
 *
 * @author Graham Campbell <graham@mineuk.com>
 */
trait PaginateProviderTrait
{
    /**
     * The paginated links generated by the paginate method.
     *
     * @var string
     */
    protected $paginateLinks;

    /**
     * Get a paginated list of the models.
     *
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function paginate()
    {
        $model = $this->model;

        if (property_exists($model, 'order')) {
            $paginator = $model::orderBy($model::$order, $model::$sort)->paginate($model::$paginate, $model::$index);
        } else {
            $paginator = $model::paginate($model::$paginate, $model::$index);
        }

        if (!$this->isPageInRange($paginator) && !$this->isFirstPage($paginator)) {
            throw new NotFoundHttpException();
        }

        if ($paginator->getTotal()) {
            $this->paginateLinks = $paginator->links();
        }

        return $paginator;
    }

    /**
     * Is this current page in range?
     *
     * @param \Illuminate\Pagination\Paginator $paginator
     *
     * @return bool
     */
    protected function isPageInRange(Paginator $paginator)
    {
        return ($paginator->getFactory()->getCurrentPage() <= $paginator->getLastPage());
    }

    /**
     * Is the current page the first page?
     *
     * @param \Illuminate\Pagination\Paginator $paginator
     *
     * @return bool
     */
    protected function isFirstPage(Paginator $paginator)
    {
        return ($paginator->getFactory()->getCurrentPage() === 1);
    }

    /**
     * Get the paginated links.
     *
     * @return string
     */
    public function links()
    {
        return $this->paginateLinks;
    }
}
